apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ tpl .Values.deployment.namespace . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ tpl .Values.deployment.selector . }}
  template:
    metadata:
      labels:
        app: {{ tpl .Values.deployment.selector . }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 45
